export const ServiceArray = [
  {
    name: "Emily Johnson",
    job: "Ac Technician",
    address: "123 Main St, Sukkur",
    number: "555-1234",
    service: [
      "Installation",
      "Maintenance and Tune-ups",
      "Repairs",
      "System Troubleshooting",
    ],
    images: [
      "/Service/AC1.png",
      "/Service/AC2.png",
      "/Service/AC3.png",
      "/Service/AC4.png",
    ],
  },
  {
    name: "Marcus Rodriguez",
    job: "Carpenter",
    address: "456 Oak St, Sukkur",
    number: "555-5678",
    service: [
      "Custom Furniture Building",
      "Cabinet Installation and Repair",
      "Woodworking and Carpentry",
      "Door and Window Installation",
    ],
    images: [
      "/Service/Car1.png",
      "/Service/Car2.png",
      "/Service/Car3.png",
      "/Service/Car4.png",
    ],
  },
  {
    name: "Olivia Patel",
    job: "Generator Technician",
    address: "789 Pine St, Sukkur",
    number: "555-9876",
    service: [
      "Routine Maintenance",
      "Engine Inspection and Repair",
      "Electrical System Diagnosis",
      "Alternator and Starter Repair",
    ],
    images: [
      "/Service/Gen1.png",
      "/Service/Gen2.png",
      "/Service/Gen3.png",
      "/Service/Gen4.png",
    ],
  },
  {
    name: "Xavier Chen",
    job: "Painter",
    address: "101 Elm St, Sukkur",
    number: "555-4321",
    service: [
      "Interior Painting",
      "Exterior Painting",
      "Wallpaper Installation",
      "Color Consultation",
    ],
    images: [
      "/Service/Pan1.png",
      "/Service/Pan2.png",
      "/Service/Pan3.png",
      "/Service/Pan4.png",
    ],
  },
  {
    name: "Jasmine Taylor",
    job: "Mason",
    address: "202 Cedar St, Sukkur",
    number: "555-8765",
    service: [
      "Bricklaying",
      "Stone Masonry",
      "Concrete Work",
      "Tile Installation",
    ],
    images: [
      "/Service/Mas1.png",
      "/Service/Mas2.png",
      "/Service/Mas3.jpg",
      "/Service/Mas4.png",
    ],
  },
];
